apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Redis
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 16.12.1
    chart: redis
  project: default
